<a href="https://colab.research.google.com/github/ashraf-badalov/ml-projects/blob/master/KNN_iris_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [223]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,f1_score, classification_report, confusion_matrix

In [224]:
data = pd.read_csv("iris.csv")
data.head()

sepal_len  sepal_wid  petal_len  petal_wid        class
0        5.1        3.5        1.4        0.2  Iris-setosa
1        4.9        3.0        1.4        0.2  Iris-setosa
2        4.7        3.2        1.3        0.2  Iris-setosa
3        4.6        3.1        1.5        0.2  Iris-setosa
4        5.0        3.6        1.4        0.2  Iris-setosa

In [225]:
data['class'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [226]:
data['class'] = data['class'].replace({"Iris-setosa":'1', "Iris-versicolor":"2", "Iris-virginica":"3"})
data.head()

sepal_len  sepal_wid  petal_len  petal_wid class
0        5.1        3.5        1.4        0.2     1
1        4.9        3.0        1.4        0.2     1
2        4.7        3.2        1.3        0.2     1
3        4.6        3.1        1.5        0.2     1
4        5.0        3.6        1.4        0.2     1

In [227]:
X = data.iloc[:,:-1]
y = data.iloc[:,-1]

In [228]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle = True, random_state=None)

In [229]:
clf = KNeighborsClassifier(n_neighbors=5)

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

In [230]:
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

0.9666666666666667


In [231]:
f1 = f1_score(y_test, y_pred, average='weighted')
print(f1) 

0.9656084656084656


In [232]:
clrp = classification_report(y_test, y_pred)
print(clrp)

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        15
           2       1.00      0.80      0.89         5
           3       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.93      0.95        30
weighted avg       0.97      0.97      0.97        30



In [233]:
confm = confusion_matrix(y_test, y_pred)
print(confm)

[[15  0  0]
 [ 0  4  1]
 [ 0  0 10]]


In [234]:
new_pred = clf.predict([[5.2, 6.1, 5.2, 0.4]])
print(new_pred)

['2']


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
